### ISSUE TITLE
Where is the --mount?

### ISSUE THREAD

**Issue by yyqAlisa** [microsoft/vscode-remote-try-python#53]
[2022-07-29T06:08:25.202Z] Step 1/10 : ARG BASE_IMAGE
[2022-07-29T06:08:25.202Z] 
Step 2/10 : FROM $BASE_IMAGE
[2022-07-29T06:08:25.202Z]  ---> 59761c125365
[2022-07-29T06:08:25.202Z] Step 3/10 : USER root
[2022-07-29T06:08:25.203Z]  ---> Using cache
[2022-07-29T06:08:25.203Z]  ---> 08fc28be8e66
Step 4/10 : ARG REMOTE_USER
[2022-07-29T06:08:25.204Z]  ---> Using cache
[2022-07-29T06:08:25.204Z]  ---> e958c639e816
Step 5/10 : ARG NEW_UID
[2022-07-29T06:08:25.204Z] 
[2022-07-29T06:08:25.204Z]  ---> Using cache
[2022-07-29T06:08:25.204Z]  ---> 748144a7871c
Step 6/10 : ARG NEW_GID
[2022-07-29T06:08:25.205Z]  ---> Using cache
[2022-07-29T06:08:25.205Z]  ---> ffda38213768
Step 7/10 : SHELL ["/bin/sh", "-c"]
[2022-07-29T06:08:25.206Z]  ---> Using cache
[2022-07-29T06:08:25.206Z]  ---> d4bd80963dbc
Step 8/10 : RUN eval $(sed -n "s/${REMOTE_USER}:[^:]*:\([^:]*\):\([^:]*\):[^:]*:\([^:]*\).*/OLD_UID=\1;OLD_GID=\2;HOME_FOLDER=\3/p" /etc/passwd); 	eval $(sed -n "s/\([^:]*\):[^:]*:${NEW_UID}:.*/EXISTING_USER=\1/p" /etc/passwd); 	eval $(sed -n "s/\([^:]*\):[^:]*:${NEW_GID}:.*/EXISTING_GROUP=\1/p" /etc/group); 	if [ -z "$OLD_UID" ]; then 		echo "Remote user not found in /etc/passwd ($REMOTE_USER)."; 	elif [ "$OLD_UID" = "$NEW_UID" -a "$OLD_GID" = "$NEW_GID" ]; then 		echo "UIDs and GIDs are the same ($NEW_UID:$NEW_GID)."; 	elif [ "$OLD_UID" != "$NEW_UID" -a -n "$EXISTING_USER" ]; then 		echo "User with UID exists ($EXISTING_USER=$NEW_UID)."; 	elif [ "$OLD_GID" != "$NEW_GID" -a -n "$EXISTING_GROUP" ]; then 		echo "Group with GID exists ($EXISTING_GROUP=$NEW_GID)."; 	else 		echo "Updating UID:GID from $OLD_UID:$OLD_GID to $NEW_UID:$NEW_GID."; 	
[2022-07-29T06:08:25.206Z] 	sed -i -e "s/\(${REMOTE_USER}:[^:]*:\)[^:]*:[^:]*/\1${NEW_UID}:${NEW_GID}/" /etc/passwd; 		if [ "$OLD_GID" != "$NEW_GID" ]; then 			sed -i -e "s/\([^:]*:[^:]*:\)${OLD_GID}:/\1${NEW_GID}:/" /etc/group; 		fi; 		chown -R $NEW_UID:$NEW_GID $HOME_FOLDER; 	fi;
[2022-07-29T06:08:25.206Z]  ---> Using cache
[2022-07-29T06:08:25.206Z]  ---> a3e4a363067a
Step 9/10 : ARG IMAGE_USER
[2022-07-29T06:08:25.207Z]  ---> Using cache
[2022-07-29T06:08:25.207Z]  ---> 6c16a26c5a40
Step 10/10 : USER $IMAGE_USER
[2022-07-29T06:08:25.208Z]  ---> Using cache
[2022-07-29T06:08:25.208Z]  ---> 7777a875b576
[2022-07-29T06:08:25.222Z] Successfully built 7777a875b576
[2022-07-29T06:08:25.225Z] Successfully tagged vsc-vscode-remote-try-python-main-16c152c2a8dd91594db8d361180c6426-uid:latest
[2022-07-29T06:08:25.227Z] Stop (6003 ms): Run: docker build -f /tmp/vsch-yyq/updateUID.Dockerfile-0.241.3 -t vsc-vscode-remote-try-python-main-16c152c2a8dd91594db8d361180c6426-uid --build-arg BASE_IMAGE=vsc-vscode-remote-try-python-main-16c152c2a8dd91594db8d361180c6426 --build-arg REMOTE_USER=vscode --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=root /tmp/vsch-yyq
[2022-07-29T06:08:25.228Z] Start: Run: docker -v
[2022-07-29T06:08:25.246Z] Stop (18 ms): Run: docker -v
[2022-07-29T06:08:25.246Z] Start: Run: docker events --format {{json .}} --filter event=start
[2022-07-29T06:08:25.248Z] Start: Starting container
[2022-07-29T06:08:25.248Z] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/app/yyq/slifeProjectVscode/vscode-remote-try-python-main,target=/workspaces/vscode-remote-try-python-main --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=/app/yyq/slifeProjectVscode/vscode-remote-try-python-main --entrypoint /bin/sh vsc-vscode-remote-try-python-main-16c152c2a8dd91594db8d361180c6426-uid -c echo Container started
[2022-07-29T06:08:25.270Z] docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /app/yyq/slifeProjectVscode/vscode-remote-try-python-main.
See 'docker run --help'.
[2022-07-29T06:08:25.271Z] Stop (23 ms): Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/app/yyq/slifeProjectVscode/vscode-remote-try-python-main,target=/workspaces/vscode-remote-try-python-main --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=/app/yyq/slifeProjectVscode/vscode-remote-try-python-main --entrypoint /bin/sh vsc-vscode-remote-try-python-main-16c152c2a8dd91594db8d361180c6426-uid -c echo Container started
[2022-07-29T06:08:25.272Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/app/yyq/slifeProjectVscode/vscode-remote-try-python-main
[2022-07-29T06:08:25.274Z] Stop (28 ms): Run: docker events --format {{json .}} --filter event=start
[2022-07-29T06:08:25.291Z] Stop (19 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/app/yyq/slifeProjectVscode/vscode-remote-try-python-main
[2022-07-29T06:08:25.292Z] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/app/yyq/slifeProjectVscode/vscode-remote-try-python-main,target=/workspaces/vscode-remote-try-python-main --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=/app/yyq/slifeProjectVscode/vscode-remote-try-python-main --entrypoint /bin/sh vsc-vscode-remote-try-python-main-16c152c2a8dd91594db8d361180c6426-uid -c echo Container started
[2022-07-29T06:08:25.292Z] trap "exit 0" 15
[2022-07-29T06:08:25.293Z] exec "$@"
[2022-07-29T06:08:25.293Z] while sleep 1 & wait $!; do :; done -
[2022-07-29T06:08:25.293Z]     at HR (/home/yyq/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:239:2183)
[2022-07-29T06:08:25.293Z]     at tb (/home/yyq/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:239:2121)
[2022-07-29T06:08:25.293Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-07-29T06:08:25.293Z]     at async QR (/home/yyq/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:2006)
[2022-07-29T06:08:25.293Z]     at async cb (/home/yyq/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:3110)
[2022-07-29T06:08:25.293Z]     at async i_ (/home/yyq/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:13194)
[2022-07-29T06:08:25.293Z]     at async n_ (/home/yyq/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:12950)
[2022-07-29T06:08:25.296Z] Stop (6981 ms): Run: /usr/share/code/code /home/yyq/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/yyq/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /app/yyq/slifeProjectVscode/vscode-remote-try-python-main --workspace-mount-consistency cached --id-label devcontainer.local_folder=/app/yyq/slifeProjectVscode/vscode-remote-try-python-main --log-level debug --log-format json --config /app/yyq/slifeProjectVscode/vscode-remote-try-python-main/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-07-29T06:08:25.296Z] Exit code 1
[2022-07-29T06:08:25.299Z] Command failed: /usr/share/code/code /home/yyq/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/yyq/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /app/yyq/slifeProjectVscode/vscode-remote-try-python-main --workspace-mount-consistency cached --id-label devcontainer.local_folder=/app/yyq/slifeProjectVscode/vscode-remote-try-python-main --log-level debug --log-format json --config /app/yyq/slifeProjectVscode/vscode-remote-try-python-main/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-07-29T06:08:25.299Z] Exit code 1

**How to solve this problem？ I want to change --mount to -v, but I can not find  --mount. 

My local path is correct. (source=/app/yyq/slifeProjectVscode/vscode-remote-try-python-main)
**

**Comment by 477447** [comment]
print("Hello, World!!! ") 
Print(" Hello, Webull! ")
