### ISSUE TITLE
Got an error when starting vscdoe in the container

### ISSUE THREAD

**Issue by barkanido** [microsoft/vscode-remote-try-python#67]
from the container logs:
```
[29 ms] Dev Containers 0.299.0 in VS Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771).
[29 ms] Start: Resolving Remote
[57 ms] Setting up container for folder or workspace: c:\Users\idobarkan\code\vscode-remote-try-node
[59 ms] Start: Run: wsl -l -v
[227 ms] Start: Run: wsl -d Ubuntu-22.04 -e /bin/sh -c echo ~
[519 ms] Start: Run: wsl -d Ubuntu-22.04 -e /bin/sh -c cd '/home/idobarkan' && /bin/sh
[535 ms] Start: Run in host: id -un
[698 ms] idobarkan
[698 ms] 
[698 ms] Start: Run in host: cat /etc/passwd
[702 ms] Start: Run in host: echo ~
[703 ms] /home/idobarkan
[703 ms] 
[704 ms] Start: Run in host: test -x '/home/idobarkan/.vscode-remote-containers/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/node'
[704 ms] 
[704 ms] 
[705 ms] Start: Run in host: test -f '/home/idobarkan/.vscode-remote-containers/dist/vscode-remote-containers-server-0.299.0.js'
[706 ms] 
[706 ms] 
[712 ms] userEnvProbe: loginInteractiveShell (default)
[713 ms] userEnvProbe: not found in cache
[715 ms] userEnvProbe shell: /bin/bash
[2245 ms] userEnvProbe PATHs:
Probe:     '/home/idobarkan/.nvm/versions/node/v18.17.0/bin:/home/idobarkan/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/PowerShell/7:/mnt/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Program Files/dotnet/:/mnt/c/Users/idobarkan/AppData/Roaming/nvm:/mnt/c/Program Files/nodejs:/mnt/c/Program Files/GitHub CLI/:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/idobarkan/.cargo/bin:/mnt/c/Users/idobarkan/AppData/Local/Programs/Python/Python311/Scripts/:/mnt/c/Users/idobarkan/AppData/Local/Programs/Python/Python311/:/mnt/c/Users/idobarkan/AppData/Local/Programs/Python/Launcher/:/mnt/c/Users/idobarkan/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/idobarkan/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Program Files/JetBrains/PyCharm 2023.1.4/bin:/mnt/c/Program Files/CMake/bin:/mnt/c/Users/idobarkan/.dotnet/tools:/mnt/c/Program Files/Neovim/bin:/mnt/c/Users/idobarkan/AppData/Local/Programs/oh-my-posh/bin:/mnt/c/Users/idobarkan/AppData/Roaming/npm:/mnt/c/Users/idobarkan/AppData/Roaming/nvm:/mnt/c/Program Files/nodejs:/snap/bin'
Container: None
[2253 ms] Start: Run in Host: wslpath -w /run/user/1000/wayland-0
[2262 ms] Start: Check Docker is running
[2262 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[2586 ms] Server API version: 1.43
[2587 ms] Start: Run: docker volume ls -q
[2820 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=c:\Users\idobarkan\code\vscode-remote-try-node --filter label=vsch.quality=stable
[3145 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node --filter label=devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json
[3403 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node
[3620 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node
[3866 ms] Start: Run: C:\Users\idobarkan\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js read-configuration --workspace-folder c:\Users\idobarkan\code\vscode-remote-try-node --id-label devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node --id-label devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --mount-workspace-git-root true
[4568 ms] @devcontainers/cli 0.46.0. Node.js v16.17.1. win32 10.0.22621 x64.
[4568 ms] Start: Run: git rev-parse --show-cdup
[4689 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node --filter label=devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json
[5427 ms] Start: Run: C:\Users\idobarkan\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\idobarkan\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-c676a5ee-d8e3-442a-b4f0-ceccaa557e7b1690281989355 --workspace-folder c:\Users\idobarkan\code\vscode-remote-try-node --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node --id-label devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Ubuntu-22.04\run\user\1000\wayland-0,target=/tmp/vscode-wayland-aab9b8c4-835b-4b82-8a96-62877209174d.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[5867 ms] @devcontainers/cli 0.46.0. Node.js v16.17.1. win32 10.0.22621 x64.
[5867 ms] Start: Run: docker buildx version
[7017 ms] github.com/docker/buildx v0.11.0 687feca9e8dcd1534ac4c026bc4db5a49de0dd6e
[7017 ms] 
[7017 ms] Start: Resolving Remote
[7021 ms] Start: Run: git rev-parse --show-cdup
[7435 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node --filter label=devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json
[7683 ms] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye
[7924 ms] local container features stored at: c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\node_modules\vscode-dev-containers\container-features
[7928 ms] Start: Run: tar --no-same-owner -x -f -
[8021 ms] Start: Run: docker events --format {{json .}} --filter event=start
[8041 ms] Start: Starting container
[8042 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=c:\Users\idobarkan\code\vscode-remote-try-node,target=/workspaces/vscode-remote-try-node,consistency=cached --mount type=volume,src=vscode,dst=/vscode --mount type=bind,src=\\wsl.localhost\Ubuntu-22.04\run\user\1000\wayland-0,dst=/tmp/vscode-wayland-aab9b8c4-835b-4b82-8a96-62877209174d.sock -l devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node -l devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --entrypoint /bin/sh -l devcontainer.metadata=[{"id":"ghcr.io/devcontainers/features/common-utils:2"},{"id":"ghcr.io/devcontainers/features/git:1"},{"id":"ghcr.io/devcontainers/features/node:1","customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}}},{"customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}},"remoteUser":"node"},{"postCreateCommand":"yarn install","customizations":{"vscode":{"settings":{},"extensions":["streetsidesoftware.code-spell-checker"]}},"portsAttributes":{"3000":{"label":"Hello Remote World","onAutoForward":"notify"}}}] mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye -c echo Container started
docker: Error response from daemon: \\wsl.localhost\Ubuntu-22.04\run\user\1000\w
ayland-0%!(EXTRA string=is not a valid Windows path).
See 'docker run --help'.
[15069 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node --filter label=devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json
[15354 ms] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=c:\Users\idobarkan\code\vscode-remote-try-node,target=/workspaces/vscode-remote-try-node,consistency=cached --mount type=volume,src=vscode,dst=/vscode --mount type=bind,src=\\wsl.localhost\Ubuntu-22.04\run\user\1000\wayland-0,dst=/tmp/vscode-wayland-aab9b8c4-835b-4b82-8a96-62877209174d.sock -l devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node -l devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --entrypoint /bin/sh -l devcontainer.metadata=[{"id":"ghcr.io/devcontainers/features/common-utils:2"},{"id":"ghcr.io/devcontainers/features/git:1"},{"id":"ghcr.io/devcontainers/features/node:1","customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}}},{"customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}},"remoteUser":"node"},{"postCreateCommand":"yarn install","customizations":{"vscode":{"settings":{},"extensions":["streetsidesoftware.code-spell-checker"]}},"portsAttributes":{"3000":{"label":"Hello Remote World","onAutoForward":"notify"}}}] mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye -c echo Container started
[15354 ms] trap "exit 0" 15
[15354 ms] exec "$@"
[15354 ms] while sleep 1 & wait $!; do :; done -
[15354 ms]     at Mte (c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2007:1066)
[15354 ms]     at n3 (c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2007:1002)
[15354 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[15354 ms]     at async rre (c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2024:3660)
[15354 ms]     at async Yf (c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2024:4775)
[15354 ms]     at async Dne (c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2156:12193)
[15354 ms]     at async Sne (c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2156:11934)
[15377 ms] Exit code 1
[15383 ms] Command failed: C:\Users\idobarkan\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\idobarkan\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-c676a5ee-d8e3-442a-b4f0-ceccaa557e7b1690281989355 --workspace-folder c:\Users\idobarkan\code\vscode-remote-try-node --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node --id-label devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Ubuntu-22.04\run\user\1000\wayland-0,target=/tmp/vscode-wayland-aab9b8c4-835b-4b82-8a96-62877209174d.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[15383 ms] Exit code 1
```

running this exact command at the root folder returns without an error and without an apparent effect:
```
 C:\Users\idobarkan\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\idobarkan\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-c676a5ee-d8e3-442a-b4f0-ceccaa557e7b1690281989355 --workspace-folder c:\Users\idobarkan\code\vscode-remote-try-node --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node --id-label devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Ubuntu-22.04\run\user\1000\wayland-0,target=/tmp/vscode-wayland-aab9b8c4-835b-4b82-8a96-62877209174d.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
```

**Comment by kengibous** [comment]
@barkanido I was able to get this to work, but I had to disable mounting Wayland socket which is a setting on the VSCode DevContainers extension.

![image](https://github.com/microsoft/vscode-remote-try-python/assets/6308070/b1631c4a-263e-4108-8b43-cf51c502e16d)

Not sure what the repercussions of changing this settings are

**Comment by Jasonford323** [comment]
[29 ms] Dev Containers 0.299.0 in VS Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771).
[29 ms] Start: Resolving Remote
[57 ms] Setting up container for folder or workspace: c:\Users\idobarkan\code\vscode-remote-try-node
[59 ms] Start: Run: wsl -l -v
[227 ms] Start: Run: wsl -d Ubuntu-22.04 -e /bin/sh -c echo ~
[519 ms] Start: Run: wsl -d Ubuntu-22.04 -e /bin/sh -c cd '/home/idobarkan' && /bin/sh
[535 ms] Start: Run in host: id -un
[698 ms] idobarkan
[698 ms] 
[698 ms] Start: Run in host: cat /etc/passwd
[702 ms] Start: Run in host: echo ~
[703 ms] /home/idobarkan
[703 ms] 
[704 ms] Start: Run in host: test -x '/home/idobarkan/.vscode-remote-containers/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/node'
[704 ms] 
[704 ms] 
[705 ms] Start: Run in host: test -f '/home/idobarkan/.vscode-remote-containers/dist/vscode-remote-containers-server-0.299.0.js'
[706 ms] 
[706 ms] 
[712 ms] userEnvProbe: loginInteractiveShell (default)
[713 ms] userEnvProbe: not found in cache
[715 ms] userEnvProbe shell: /bin/bash
[2245 ms] userEnvProbe PATHs:
Probe:     '/home/idobarkan/.nvm/versions/node/v18.17.0/bin:/home/idobarkan/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/PowerShell/7:/mnt/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Program Files/dotnet/:/mnt/c/Users/idobarkan/AppData/Roaming/nvm:/mnt/c/Program Files/nodejs:/mnt/c/Program Files/GitHub CLI/:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/idobarkan/.cargo/bin:/mnt/c/Users/idobarkan/AppData/Local/Programs/Python/Python311/Scripts/:/mnt/c/Users/idobarkan/AppData/Local/Programs/Python/Python311/:/mnt/c/Users/idobarkan/AppData/Local/Programs/Python/Launcher/:/mnt/c/Users/idobarkan/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/idobarkan/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Program Files/JetBrains/PyCharm 2023.1.4/bin:/mnt/c/Program Files/CMake/bin:/mnt/c/Users/idobarkan/.dotnet/tools:/mnt/c/Program Files/Neovim/bin:/mnt/c/Users/idobarkan/AppData/Local/Programs/oh-my-posh/bin:/mnt/c/Users/idobarkan/AppData/Roaming/npm:/mnt/c/Users/idobarkan/AppData/Roaming/nvm:/mnt/c/Program Files/nodejs:/snap/bin'
Container: None
[2253 ms] Start: Run in Host: wslpath -w /run/user/1000/wayland-0
[2262 ms] Start: Check Docker is running
[2262 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[2586 ms] Server API version: 1.43
[2587 ms] Start: Run: docker volume ls -q
[2820 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=c:\Users\idobarkan\code\vscode-remote-try-node --filter label=vsch.quality=stable
[3145 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node --filter label=devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json
[3403 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node
[3620 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node
[3866 ms] Start: Run: C:\Users\idobarkan\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js read-configuration --workspace-folder c:\Users\idobarkan\code\vscode-remote-try-node --id-label devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node --id-label devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --mount-workspace-git-root true
[4568 ms] @devcontainers/cli 0.46.0. Node.js v16.17.1. win32 10.0.22621 x64.
[4568 ms] Start: Run: git rev-parse --show-cdup
[4689 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node --filter label=devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json
[5427 ms] Start: Run: C:\Users\idobarkan\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\idobarkan\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-c676a5ee-d8e3-442a-b4f0-ceccaa557e7b1690281989355 --workspace-folder c:\Users\idobarkan\code\vscode-remote-try-node --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node --id-label devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Ubuntu-22.04\run\user\1000\wayland-0,target=/tmp/vscode-wayland-aab9b8c4-835b-4b82-8a96-62877209174d.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[5867 ms] @devcontainers/cli 0.46.0. Node.js v16.17.1. win32 10.0.22621 x64.
[5867 ms] Start: Run: docker buildx version
[7017 ms] github.com/docker/buildx v0.11.0 687feca9e8dcd1534ac4c026bc4db5a49de0dd6e
[7017 ms] 
[7017 ms] Start: Resolving Remote
[7021 ms] Start: Run: git rev-parse --show-cdup
[7435 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node --filter label=devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json
[7683 ms] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye
[7924 ms] local container features stored at: c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\node_modules\vscode-dev-containers\container-features
[7928 ms] Start: Run: tar --no-same-owner -x -f -
[8021 ms] Start: Run: docker events --format {{json .}} --filter event=start
[8041 ms] Start: Starting container
[8042 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=c:\Users\idobarkan\code\vscode-remote-try-node,target=/workspaces/vscode-remote-try-node,consistency=cached --mount type=volume,src=vscode,dst=/vscode --mount type=bind,src=\\wsl.localhost\Ubuntu-22.04\run\user\1000\wayland-0,dst=/tmp/vscode-wayland-aab9b8c4-835b-4b82-8a96-62877209174d.sock -l devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node -l devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --entrypoint /bin/sh -l devcontainer.metadata=[{"id":"ghcr.io/devcontainers/features/common-utils:2"},{"id":"ghcr.io/devcontainers/features/git:1"},{"id":"ghcr.io/devcontainers/features/node:1","customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}}},{"customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}},"remoteUser":"node"},{"postCreateCommand":"yarn install","customizations":{"vscode":{"settings":{},"extensions":["streetsidesoftware.code-spell-checker"]}},"portsAttributes":{"3000":{"label":"Hello Remote World","onAutoForward":"notify"}}}] mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye -c echo Container started
docker: Error response from daemon: \\wsl.localhost\Ubuntu-22.04\run\user\1000\w
ayland-0%!(EXTRA string=is not a valid Windows path).
See 'docker run --help'.
[15069 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node --filter label=devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json
[15354 ms] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=c:\Users\idobarkan\code\vscode-remote-try-node,target=/workspaces/vscode-remote-try-node,consistency=cached --mount type=volume,src=vscode,dst=/vscode --mount type=bind,src=\\wsl.localhost\Ubuntu-22.04\run\user\1000\wayland-0,dst=/tmp/vscode-wayland-aab9b8c4-835b-4b82-8a96-62877209174d.sock -l devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node -l devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --entrypoint /bin/sh -l devcontainer.metadata=[{"id":"ghcr.io/devcontainers/features/common-utils:2"},{"id":"ghcr.io/devcontainers/features/git:1"},{"id":"ghcr.io/devcontainers/features/node:1","customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}}},{"customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}},"remoteUser":"node"},{"postCreateCommand":"yarn install","customizations":{"vscode":{"settings":{},"extensions":["streetsidesoftware.code-spell-checker"]}},"portsAttributes":{"3000":{"label":"Hello Remote World","onAutoForward":"notify"}}}] mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye -c echo Container started
[15354 ms] trap "exit 0" 15
[15354 ms] exec "$@"
[15354 ms] while sleep 1 & wait $!; do :; done -
[15354 ms]     at Mte (c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2007:1066)
[15354 ms]     at n3 (c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2007:1002)
[15354 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[15354 ms]     at async rre (c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2024:3660)
[15354 ms]     at async Yf (c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2024:4775)
[15354 ms]     at async Dne (c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2156:12193)
[15354 ms]     at async Sne (c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2156:11934)
[15377 ms] Exit code 1
[15383 ms] Command failed: C:\Users\idobarkan\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\idobarkan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\idobarkan\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-c676a5ee-d8e3-442a-b4f0-ceccaa557e7b1690281989355 --workspace-folder c:\Users\idobarkan\code\vscode-remote-try-node --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\idobarkan\code\vscode-remote-try-node --id-label devcontainer.config_file=c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\idobarkan\code\vscode-remote-try-node\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Ubuntu-22.04\run\user\1000\wayland-0,target=/tmp/vscode-wayland-aab9b8c4-835b-4b82-8a96-62877209174d.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[15383 ms] Exit code 1
```python

```

**Comment by Annajanet** [comment]
![image](https://github.com/microsoft/vscode-remote-try-python/assets/121921817/8164c14c-daec-418f-b8af-cc869464f108)
